-d E:\stuff\dh\thiet_ket_vi_mach\do_an_tot_nghiep\verilog\pwm_i2c\impl\gwsynthesis\pwm_i2c.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst E:\stuff\dh\thiet_ket_vi_mach\do_an_tot_nghiep\verilog\pwm_i2c\src\pwm_i2c.cst
-cfg E:\stuff\dh\thiet_ket_vi_mach\do_an_tot_nghiep\verilog\pwm_i2c\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
